Repository nasa/SC, pull requests merged in 2022-06, with the labels that each got.

#34 Fix #33, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Corp_CLA_SC_310.pdf
  docs/Indv_CLA_SC_310.pdf
Labels: docs, CCB:Approved

#30 Fix #29, Added codeql-build.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency

#37 Fix #15 #21 #36, Code coverage improvements
  .github/workflows/unit-test-coverage.yml
  fsw/src/sc_cmds.c
  fsw/src/sc_state.c
  unit-test/sc_app_tests.c
  unit-test/sc_loads_tests.c
Labels: CCB:Approved
