Repository nasa/SC, pull requests merged in 2023-09, with the labels that each got.

#97 Fix #96, Moved command validation out of command functions
  fsw/src/sc_atsrq.c
  fsw/src/sc_cmds.c
  fsw/src/sc_rtsrq.c
  unit-test/sc_atsrq_tests.c
  unit-test/sc_cmds_tests.c
  unit-test/sc_rtsrq_tests.c
Labels: CCB:Approved, Equuleus-rc2

#100 Fix #99, cmd and tlm messages use payload sub-structure
  fsw/inc/sc_msg.h
  fsw/inc/sc_msgdefs.h
  fsw/src/sc_app.c
  fsw/src/sc_atsrq.c
  fsw/src/sc_cmds.c
  fsw/src/sc_loads.c
  fsw/src/sc_rtsrq.c
  fsw/src/sc_state.c
  fsw/src/sc_utils.c
  fsw/tables/sc_ats1.c
  fsw/tables/sc_rts001.c
  unit-test/sc_app_tests.c
  unit-test/sc_atsrq_tests.c
  unit-test/sc_cmds_tests.c
  unit-test/sc_loads_tests.c
  unit-test/sc_rtsrq_tests.c
  unit-test/sc_state_tests.c
  unit-test/sc_utils_tests.c
Labels: CCB:Approved, Equuleus-rc2

#46 Fix #8, reorder conditions in if statements to optimize code
  fsw/src/sc_cmds.c
Labels: enhancement, CCB:Approved

#106 Fix #105, remove SC_ENABLE_GROUP_COMMANDS option
  fsw/inc/sc_events.h
  fsw/inc/sc_msg.h
  fsw/inc/sc_msgdefs.h
  fsw/inc/sc_platform_cfg.h
  fsw/src/sc_cmds.c
  fsw/src/sc_rtsrq.c
  fsw/src/sc_rtsrq.h
  fsw/src/sc_verify.h
  unit-test/utilities/sc_test_utils.h
Labels: CCB:Approved

#110 Fix #109, use generated stubs in unit tests
  unit-test/CMakeLists.txt
  unit-test/stubs/sc_app_stubs.c
  unit-test/stubs/sc_atsrq_stubs.c
  unit-test/stubs/sc_cmds_stubs.c
  unit-test/stubs/sc_global_stubs.c
  unit-test/stubs/sc_loads_stubs.c
  unit-test/stubs/sc_rtsrq_stubs.c
  unit-test/stubs/sc_state_stubs.c
  unit-test/stubs/sc_utils_stubs.c
Labels: CCB:Approved
